### ISSUE TITLE
Add more functionality

### ISSUE THREAD

**Issue by debck** [debck/File-Creator-CLI#10]

**Comment by thesmallstar** [comment]
I will add them :)

**Comment by debck** [comment]
@thesmallstar  Nice :tada: . so, which functionality do you want to add?

**Comment by thesmallstar** [comment]
@debck 
 I will try to add:
1. Delete option.
2. Rename option.
3. File size option
Anything you would suggest?

**Comment by debck** [comment]
That would be great. 👍   You can continue working on that and if u need any help, do reach out

**Comment by thesmallstar** [comment]
@debck 
Update: I have added delete function and it works great. 
I wanted to know if I can change the command that starts CLI(create) since the CLI now does more than just creating a file. 
Shortly, I would be adding other two features. 
You may check the code: https://github.com/thesmallstar/File-Creator-CLI

**Comment by thesmallstar** [comment]
I think you would agree on this, to simplify commands I was thinking to keep the main d/f commands same and only add one new command' (more) that gives access to other options like delete/size/rename.

**Comment by debck** [comment]
Ya that would also be nice. 👍

**Comment by thesmallstar** [comment]
@debck  
update: Rename file,filesize option is added.
I will now clean the code up and separate logics. 
I find that typing name and then an extension for a file is really annoying, when repeated I think we can take input simply as filename.extension what do you think of this?

**Comment by debck** [comment]
Ok if thats annoying for users then we should remove that. 👍 
U can proceed with the change

**Comment by debck** [comment]
For now, I think let it ask question whether it is a file or a directory to be created. 👍 We can change it later if thats become little frustating.

**Comment by thesmallstar** [comment]
Can you tell me about testing and how should I do it? I am new to this. Haven't done it before.

**Comment by debck** [comment]
@thesmallstar  Answering in slack. 😄

**Comment by debck** [comment]
Hey @thesmallstar . To test run `npm run test` in the root of the project. You can see the details whether the test fails or passes. We have used [jest](https://jestjs.io/) to test our application.
