### ISSUE TITLE
Add successful statement after executing each command

### ISSUE THREAD

**Issue by debck** [debck/File-Creator-CLI#21]
While creating file we get this output as : `File successsfully created!!!`
![file](https://user-images.githubusercontent.com/33368759/51422934-d2363100-1bdd-11e9-89da-181cfa1d687a.PNG)

However for some command like deleting file` df ` it doesn,t show any output
![fileoriginal](https://user-images.githubusercontent.com/33368759/51422935-d3fff480-1bdd-11e9-8a3d-1cac27d8aae1.PNG)

Check for all the functions and add the specific execution statement at last.

**Comment by debck** [comment]
Yes @thesmallstar  you can continue working

**Comment by debck** [comment]
@thesmallstar are you still working on this issue. If you need any help , you can ask me in the slack

**Comment by thesmallstar** [comment]
@debck  I have already solved the issue, I am again facing problems in git-specifically. If not solved by today, I will ask you on slack :)
