### ISSUE TITLE
Improve initial question representation

### ISSUE THREAD

**Issue by debck** [debck/File-Creator-CLI#32]
For now it shows: 
![capture](https://user-images.githubusercontent.com/33368759/52322621-d5b02180-29ff-11e9-9d33-ee0212648480.PNG) 
It looks very clumsy and odd. Try to improve it and make it more specific and clear.

**Comment by thesmallstar** [comment]
I will try it :)

**Comment by debck** [comment]
Go on 👍

**Comment by thesmallstar** [comment]
@debck  since the number of commands are too many, I was thinking to design it in the following way, User can enter a command directly and he would get a message-  Enter command ( enter help ro see available commands) : 

and then help would display all commands, what are your views?

**Comment by debck** [comment]
@thesmallstar I was also thinking of the same.
Yes, you can implement that

**Comment by thesmallstar** [comment]
@debck  ok :)
