### ISSUE TITLE
Improve Header Design

### ISSUE THREAD

**Issue by debck** [debck/File-Creator-CLI#9]

**Comment by lassiecoder** [comment]
I'll be handling this issue.

**Comment by debck** [comment]
👍 @lassiecoder  carry on.

**Comment by lassiecoder** [comment]
What are the requirements?

**Comment by debck** [comment]
There is no such requirement. I think, changing the initial header would be good. But, you are free to do anything 👍

**Comment by sourabh1031** [comment]
i will work on this.

**Comment by sourabh1031** [comment]
Which header you are talking about ?

**Comment by debck** [comment]
This header which is displayed  when u run the application

![capture](https://user-images.githubusercontent.com/33368759/51845074-cdd7e980-233c-11e9-95e5-9d81ef69481d.PNG)

**Comment by sourabh1031** [comment]
Okay I will take up the issue

**Comment by sourabh1031** [comment]
Can you please tell me any resource to make this
